from playwright.async_api import async_playwright
import asyncio

async def test_recorded_actions():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        page = await browser.new_page()
        await page.goto('https://test.teamstreamz.com/')
        await page.click('#Username')
        await page.fill('#Username', 'k')
        await page.fill('#Username', 'ku')
        await page.fill('#Username', 'kus')
        await page.fill('#Username', 'kush')
        await page.fill('#Username', 'kusha')
        await page.fill('#Username', 'kushal')
        await page.fill('#Username', 'kushal.')
        await page.fill('#Username', 'kushal.j')
        await page.fill('#Username', 'kushal.je')
        await page.fill('#Username', 'kushal.jet')
        await page.fill('#Username', 'kushal.jett')
        await page.fill('#Username', 'kushal.jetty')
        await page.fill('#Username', 'kushal.jetty@')
        await page.fill('#Username', 'kushal.jetty@t')
        await page.fill('#Username', 'kushal.jetty@te')
        await page.fill('#Username', 'kushal.jetty@tea')
        await page.fill('#Username', 'kushal.jetty@team')
        await page.fill('#Username', 'kushal.jetty@teams')
        await page.fill('#Username', 'kushal.jetty@teamst')
        await page.fill('#Username', 'kushal.jetty@teamstr')
        await page.fill('#Username', 'kushal.jetty@teamstre')
        await page.fill('#Username', 'kushal.jetty@teamstrea')
        await page.fill('#Username', 'kushal.jetty@teamstream')
        await page.fill('#Username', 'kushal.jetty@teamstreamz')
        await page.fill('#Username', 'kushal.jetty@teamstreamz.')
        await page.fill('#Username', 'kushal.jetty@teamstreamz.c')
        await page.fill('#Username', 'kushal.jetty@teamstreamz.co')
        await page.fill('#Username', 'kushal.jetty@teamstreamz.com')
        await page.click('#Password')
        await page.fill('#Password', 'T')
        await page.fill('#Password', 'Te')
        await page.fill('#Password', 'Tes')
        await page.fill('#Password', 'Test')
        await page.fill('#Password', 'Test@')
        await page.fill('#Password', 'Test@1')
        await page.fill('#Password', 'Test@12')
        await page.fill('#Password', 'Test@123')
        await page.click('.btn.signin-btn.bg-primary.ng-tns-c813547932-0')
        await page.click('span')
        await page.click('.btn-ts.btn-ts-primary.ng-star-inserted')
        await page.click('.btn-close')
        await page.click('#user-action-icon')
        await page.click('.change-pwd')
        await browser.close()
asyncio.run(test_recorded_actions())