import os
import sys
import unittest
import importlib.util
import time
import logging
import subprocess
from pathlib import Path
from typing import Dict, List, Any, Tuple, Optional

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler("test_runner.log"),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger("StreamzAI-TestRunner")

class StreamzAITestRunner:
    """Class for running test cases generated by StreamzAI."""
    
    def __init__(self, test_files: List[str] = None, is_django: bool = False, django_project_path: str = None):
        """Initialize the test runner.
        
        Args:
            test_files: List of test files to run
            is_django: Whether the tests are for a Django project
            django_project_path: Path to the Django project root
        """
        self.test_files = test_files or []
        self.results = {}
        self.is_django = is_django
        self.django_project_path = django_project_path
    
    def discover_tests(self, test_dir: str) -> List[str]:
        """Discover test files in a directory.
        
        Args:
            test_dir: Directory to search for test files
            
        Returns:
            List of test file paths
        """
        test_files = []
        try:
            for root, _, files in os.walk(test_dir):
                for file in files:
                    if file.startswith('test_') and file.endswith('.py'):
                        test_files.append(os.path.join(root, file))
            
            logger.info(f"Discovered {len(test_files)} test files in {test_dir}")
            return test_files
        except Exception as e:
            logger.error(f"Error discovering tests in {test_dir}: {str(e)}")
            return []
    
    def load_test_from_file(self, file_path: str) -> Tuple[unittest.TestSuite, Optional[str]]:
        """Load tests from a file into a test suite.
        
        Args:
            file_path: Path to the test file
            
        Returns:
            Tuple of (test_suite, error_message)
        """
        try:
            # Get module name from file path
            module_name = os.path.splitext(os.path.basename(file_path))[0]
            
            # Load module from file path
            spec = importlib.util.spec_from_file_location(module_name, file_path)
            if spec is None or spec.loader is None:
                return unittest.TestSuite(), f"Could not load spec for {file_path}"
            
            module = importlib.util.module_from_spec(spec)
            sys.modules[module_name] = module
            spec.loader.exec_module(module)
            
            # Create test suite from module
            loader = unittest.TestLoader()
            suite = loader.loadTestsFromModule(module)
            
            return suite, None
        except Exception as e:
            logger.error(f"Error loading tests from {file_path}: {str(e)}")
            return unittest.TestSuite(), str(e)
    
    def run_django_test(self, file_path: str) -> Dict[str, Any]:
        """Run Django tests from a single file.
        
        Args:
            file_path: Path to the test file
            
        Returns:
            Dictionary with test results
        """
        start_time = time.time()
        
        # Get the test module name from the file path
        module_name = os.path.splitext(os.path.basename(file_path))[0]
        
        # Prepare the Django test command
        cmd = [
            sys.executable,  # Python executable
            os.path.join(self.django_project_path, "manage.py"),  # Django manage.py
            "test",  # Test command
            module_name  # Test module name
        ]
        
        # Set the working directory to the Django project path
        cwd = self.django_project_path
        
        try:
            # Run the Django test command
            logger.info(f"Running Django test: {' '.join(cmd)}")
            process = subprocess.Popen(
                cmd,
                cwd=cwd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
            )
            stdout, stderr = process.communicate()
            
            end_time = time.time()
            execution_time = end_time - start_time
            
            # Process the test results
            if process.returncode == 0:
                # Tests passed
                status = "passed"
                tests = [{
                    "name": module_name,
                    "status": "passed",
                    "error_message": None
                }]
                total_tests = 1
                passed_tests = 1
                failed_tests = 0
                error_tests = 0
                skipped_tests = 0
            else:
                # Tests failed
                status = "failed"
                tests = [{
                    "name": module_name,
                    "status": "failed",
                    "error_message": stderr or stdout
                }]
                total_tests = 1
                passed_tests = 0
                failed_tests = 1
                error_tests = 0
                skipped_tests = 0
            
            return {
                "file_path": file_path,
                "status": status,
                "execution_time": execution_time,
                "tests": tests,
                "total": total_tests,
                "passed": passed_tests,
                "failed": failed_tests,
                "errors": error_tests,
                "skipped": skipped_tests,
                "stdout": stdout,
                "stderr": stderr
            }
        except Exception as e:
            end_time = time.time()
            return {
                "file_path": file_path,
                "status": "error",
                "error_message": str(e),
                "execution_time": end_time - start_time,
                "tests": [],
                "total": 0,
                "passed": 0,
                "failed": 0,
                "errors": 1,
                "skipped": 0
            }
    
    def run_test_file(self, file_path: str) -> Dict[str, Any]:
        """Run tests from a single file.
        
        Args:
            file_path: Path to the test file
            
        Returns:
            Dictionary with test results
        """
        # If this is a Django test and we have a Django project path, use the Django test runner
        if self.is_django and self.django_project_path:
            return self.run_django_test(file_path)
        
        start_time = time.time()
        
        # Load tests from file
        suite, error = self.load_test_from_file(file_path)
        
        if error:
            end_time = time.time()
            return {
                "file_path": file_path,
                "status": "error",
                "error_message": error,
                "execution_time": end_time - start_time,
                "tests": [],
                "total": 0,
                "passed": 0,
                "failed": 0,
                "errors": 1,
                "skipped": 0
            }
        
        # Run tests
        result = unittest.TestResult()
        suite.run(result)
        
        end_time = time.time()
        execution_time = end_time - start_time
        
        # Process test results
        tests = []
        for test, err in result.errors:
            tests.append({
                "name": str(test),
                "status": "error",
                "error_message": err
            })
        
        for test, err in result.failures:
            tests.append({
                "name": str(test),
                "status": "failed",
                "error_message": err
            })
        
        for test in result.skipped:
            tests.append({
                "name": str(test[0]),
                "status": "skipped",
                "error_message": test[1]
            })
        
        # Add passed tests
        for test in suite:
            test_id = test.id()
            if not any(t["name"] == test_id for t in tests):
                tests.append({
                    "name": test_id,
                    "status": "passed",
                    "error_message": None
                })
        
        # Determine overall status
        if result.errors or result.failures:
            status = "failed"
        elif result.skipped and not result.wasSuccessful():
            status = "skipped"
        else:
            status = "passed"
        
        return {
            "file_path": file_path,
            "status": status,
            "execution_time": execution_time,
            "tests": tests,
            "total": result.testsRun,
            "passed": result.testsRun - len(result.errors) - len(result.failures) - len(result.skipped),
            "failed": len(result.failures),
            "errors": len(result.errors),
            "skipped": len(result.skipped)
        }
    
    def run_tests(self, test_files: List[str] = None) -> Dict[str, Any]:
        """Run tests from multiple files.
        
        Args:
            test_files: List of test files to run. If None, uses self.test_files.
            
        Returns:
            Dictionary with test results
        """
        test_files = test_files or self.test_files
        if not test_files:
            logger.warning("No test files specified")
            return {
                "status": "error",
                "error_message": "No test files specified",
                "file_results": [],
                "summary": {
                    "total_files": 0,
                    "passed_files": 0,
                    "failed_files": 0,
                    "error_files": 0,
                    "total_tests": 0,
                    "passed_tests": 0,
                    "failed_tests": 0,
                    "error_tests": 0,
                    "skipped_tests": 0,
                    "execution_time": 0
                }
            }
        
        start_time = time.time()
        file_results = []
        
        # Run tests for each file
        for file_path in test_files:
            logger.info(f"Running tests from {file_path}")
            result = self.run_test_file(file_path)
            file_results.append(result)
        
        end_time = time.time()
        total_execution_time = end_time - start_time
        
        # Calculate summary
        total_files = len(file_results)
        passed_files = sum(1 for r in file_results if r["status"] == "passed")
        failed_files = sum(1 for r in file_results if r["status"] == "failed")
        error_files = sum(1 for r in file_results if r["status"] == "error")
        
        total_tests = sum(r["total"] for r in file_results)
        passed_tests = sum(r["passed"] for r in file_results)
        failed_tests = sum(r["failed"] for r in file_results)
        error_tests = sum(r["errors"] for r in file_results)
        skipped_tests = sum(r["skipped"] for r in file_results)
        
        summary = {
            "total_files": total_files,
            "passed_files": passed_files,
            "failed_files": failed_files,
            "error_files": error_files,
            "total_tests": total_tests,
            "passed_tests": passed_tests,
            "failed_tests": failed_tests,
            "error_tests": error_tests,
            "skipped_tests": skipped_tests,
            "execution_time": total_execution_time
        }
        
        # Determine overall status
        if error_files > 0:
            status = "error"
        elif failed_files > 0:
            status = "failed"
        else:
            status = "passed"
        
        return {
            "status": status,
            "file_results": file_results,
            "summary": summary
        }


def main():
    """Main entry point for the test runner."""
    import argparse
    
    parser = argparse.ArgumentParser(description="StreamzAI Test Runner")
    parser.add_argument("--test-dir", help="Directory containing test files")
    parser.add_argument("--test-file", help="Specific test file to run")
    parser.add_argument("--output", help="Output file for test results (JSON)")
    parser.add_argument("--verbose", "-v", action="store_true", help="Enable verbose output")
    parser.add_argument("--django", action="store_true", help="Run tests for a Django project")
    parser.add_argument("--django-project-path", help="Path to the Django project root")
    parser.add_argument("--test-summary-file", help="Path to the test generation summary JSON file")
    
    args = parser.parse_args()
    
    if args.verbose:
        logger.setLevel(logging.DEBUG)
    
    # Initialize the test runner
    runner = StreamzAITestRunner(
        is_django=args.django,
        django_project_path=args.django_project_path
    )
    
    # Load test files from summary file if provided
    if args.test_summary_file and os.path.exists(args.test_summary_file):
        try:
            with open(args.test_summary_file, 'r') as f:
                summary = json.load(f)
                test_files = [item['test_file'] for item in summary.get('test_files', [])]
                logger.info(f"Loaded {len(test_files)} test files from summary file")
        except Exception as e:
            logger.error(f"Error loading test summary file: {str(e)}")
            return 1
    elif args.test_file:
        test_files = [args.test_file]
    elif args.test_dir:
        test_files = runner.discover_tests(args.test_dir)
    else:
        logger.error("Either --test-dir, --test-file, or --test-summary-file must be specified")
        return 1
    
    results = runner.run_tests(test_files)
    
    # Print summary
    summary = results["summary"]
    print("\nTest Run Summary:")
    print(f"Status: {results['status']}")
    print(f"Total files: {summary['total_files']}")
    print(f"Passed files: {summary['passed_files']}")
    print(f"Failed files: {summary['failed_files']}")
    print(f"Error files: {summary['error_files']}")
    print(f"Total tests: {summary['total_tests']}")
    print(f"Passed tests: {summary['passed_tests']}")
    print(f"Failed tests: {summary['failed_tests']}")
    print(f"Error tests: {summary['error_tests']}")
    print(f"Skipped tests: {summary['skipped_tests']}")
    print(f"Execution time: {summary['execution_time']:.2f} seconds")
    
    # Save results to file if specified
    if args.output:
        import json
        with open(args.output, 'w', encoding='utf-8') as f:
            json.dump(results, f, indent=2)
        print(f"\nResults saved to {args.output}")
    
    return 0 if results["status"] == "passed" else 1


if __name__ == "__main__":
    sys.exit(main())