"""Add active column for soft delete

Revision ID: 1f271c1342ab
Revises: 
Create Date: 2025-04-23 12:19:55.444461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f271c1342ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'active' column with default=True (use server_default for SQLite compatibility)
    for table in ['project', 'test_suite', 'test_case', 'test_run']:
        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    'active', 
                    sa.Boolean(), 
                    nullable=False, 
                    server_default=sa.text('1')  # Set default=True (1 for SQLite)
                )
            )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_suite', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('test_run', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('test_case', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
