import unittest
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
import time

class test1(unittest.TestCase):
    def setUp(self):
        chrome_options = Options()
        chrome_options.add_argument("--start-maximized")
        self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)
        self.wait = WebDriverWait(self.driver, 10)
        
    def test_main(self):
        driver = self.driver
        wait = self.wait
        driver.get('https://test.teamstreamz.com/')
    element = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, '#Username')))
                element.click()
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('k')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('ku')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kus')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kush')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kusha')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushalj')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.j')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.je')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jet')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jett')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty@')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty@t')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty@te')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty@tea')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty@team')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty@teams')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty@teamst')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty@teamstr')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty@teamstre')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty@teamstrea')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty@teamstream')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty@teamstreamz')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty@teamstreamz.')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty@teamstreamz.c')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty@teamstreamz.co')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty@teamstreamz.com')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
                element.clear()
                element.send_keys('kushal.jetty@teamstreamz.com')
    element = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, '#Password')))
                element.click()
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Password')))
                element.clear()
                element.send_keys('J')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Password')))
                element.clear()
                element.send_keys('')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Password')))
                element.clear()
                element.send_keys('T')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Password')))
                element.clear()
                element.send_keys('Te')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Password')))
                element.clear()
                element.send_keys('Tes')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Password')))
                element.clear()
                element.send_keys('Test')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Password')))
                element.clear()
                element.send_keys('Test@')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Password')))
                element.clear()
                element.send_keys('Test@1')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Password')))
                element.clear()
                element.send_keys('Test@12')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Password')))
                element.clear()
                element.send_keys('Test@123')
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Password')))
                element.clear()
                element.send_keys('Test@123')
    element = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, \
        'button.btn.signin-btn.bg-primary.ng-tns-c813547932-0')))
                element.click()
    element = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR,\
        'a.list-group-item.inactive-link.ng-star-inserted')))
                element.click()
    element = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, \
        'body:nth-child(2) > app-root:nth-child(1) > app-layout:nth-child(2) > \
            app-sidebar:nth-child(2) > nav > div:nth-child(1) > div:nth-child(3) > div \
                > a > span:nth-child(2)')))
    element.click()

def tearDown(self):
    self.driver.quit()
    
if __name__ == "__main__":
    unittest.main()
            