import unittest
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
import time

class AutoGeneratedTest(unittest.TestCase):
    def setUp(self):
        chrome_options = Options()
        chrome_options.add_argument("--start-maximized")
        self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)
        self.wait = WebDriverWait(self.driver, 10)

    def test_main(self):
        driver = self.driver
        wait = self.wait
        driver.get('https://test.teamstreamz.com/')
        element = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, '#Username')))
        element.click()
        element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Username')))
        element.clear()
        element.send_keys('kushal.jetty@teamstreamz.com')
        element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '#Password')))
        element.clear()
        element.send_keys('Test@123')
        element = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, 'button.btn.signin-btn.bg-primary.ng-tns-c813547932-0')))
        element.click()
        element = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, 'div.ng-tns-c1499558128-1.ng-trigger.ng-trigger-routerTransition')))
        element.click()

    def tearDown(self):
        self.driver.quit()

if __name__ == "__main__":
    unittest.main()
            