from playwright.async_api import async_playwright
import asyncio

async def test_recorded_actions():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        page = await browser.new_page()
        await page.goto('https://test.teamstreamz.com/')
        await page.click('#Username')
        await page.fill('#Username', 'kushal.jetty@teamstreamz.com')
        await page.fill('#Password', 'Test@123')
        await page.click('.btn.signin-btn.bg-primary.ng-tns-c813547932-0')
        await page.click('span')
        await page.click('.btn-ts.btn-ts-primary')
        await page.click('input')
        await page.click('#stream-title')
        await page.click('input')
        await page.fill('input', 'english (india)')
        await page.click('#stream-title')
        await page.fill('#stream-title', 'test demo1')
        await page.click('#stream-desc')
        await page.fill('#stream-desc', 'test demo1 desc')
        await page.click('.croppie-input')
        await page.fill('.croppie-input', 'C:\fakepath\test.jpg')
        await page.click('.btn-ts.btn-ts-primary.ng-star-inserted')
        await page.click('.btn-ts.btn-ts-primary-outline.ng-star-inserted')
        await page.click('.pad-left-26.custom-checkbox-label-text')
        await page.click('[name="streamOthers"]')
        await page.click('.pad-left-26.custom-checkbox-label-text')
        await page.click('[name="streamOthers"]')
        await page.click('.checkmark')
        await page.click('[name="streamOthers"]')
        await page.fill('[name="streamOthers"]', 'alertOnExpiry')
        await page.click('.btn-ts.ng-star-inserted.btn-ts-primary')
        await page.click('#section-title')
        await page.fill('#section-title', 'demo title')
        await page.click('#main-obj-1')
        await page.fill('#main-obj-1', '66369')
        await page.click('.ng-input')
        await page.click('#a296196c2a4b-0')
        await page.click('.btn-ts.btn-ts-primary.ng-star-inserted')
        await page.click('.btn-ts.btn-ts-primary.ng-star-inserted')
        await page.click('img')
        await page.click('h5')
        await page.click('#18257')
        await page.click('.dropdown-item')
        await page.click('.btn-ts.btn-ts-primary.restrictedButton')
        await page.click('.change-pwd')
        await browser.close()
asyncio.run(test_recorded_actions())